repos:
    - repo: local
      hooks:
          - id: eslint
            name: eslint
            entry: npx eslint --fix
            language: system
            types_or: [ts, javascript]
          - id: prettier
            name: prettier
            entry: npx prettier --write --ignore-unknown
            language: system
            types_or: [ts, javascript, json, yaml, markdown, html, css, scss]
          - id: typecheck
            name: typecheck
            entry: npx tsc --noEmit
            language: system
            types_or: [ts]
            pass_filenames: false
